node:
  cluster: demo
  id: demo
admin:
  address:
    socket_address:
      address: 127.0.0.1
      port_value: 9901
static_resources:
  listeners:
  - name: demo
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 8080
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          codec_type: AUTO
          stat_prefix: ingress_http
          access_log:
          - name: envoy.access_loggers.stdout
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog
          route_config:
            name: test_route
            virtual_hosts:
            - name: www
              domains:
              - "*"
              routes:
              - match:
                  prefix: "/"
                route:
                  cluster: backend
                  auto_host_rewrite: true

          http_filters:
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
              upstream_http_filters: 
                - name: envoy.filters.http.ext_proc
                  typed_config:
                    "@type": "type.googleapis.com/envoy.extensions.filters.http.ext_proc.v3.ExternalProcessor"
                    failure_mode_allow: false
                    message_timeout: 120s
                    processing_mode:
                      request_header_mode: "SEND"
                      response_header_mode: "SKIP"
                      request_body_mode: "NONE"
                      response_body_mode: "NONE"
                      request_trailer_mode: "SKIP"
                      response_trailer_mode: "SKIP"
                    request_attributes:
                      - "upstream.address"
                      - "upstream.local_address"
                      - "upstream.port"
                    grpc_service:
                      envoy_grpc:
                        cluster_name: ext-proc
                - name: envoy.filters.http.upstream_codec
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.filters.http.upstream_codec.v3.UpstreamCodec
  clusters:
  - name: backend
    connect_timeout: 5s
    type: LOGICAL_DNS
    dns_lookup_family: V4_ONLY
    load_assignment:
      cluster_name: backend
      endpoints:
        - lb_endpoints:
            - endpoint:
                address:
                  socket_address: 
                    address: webhook.site
                    port_value: 443      
    transport_socket:
      name: envoy.transport_sockets.tls
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
        sni: webhook.site
        common_tls_context:
          validation_context:
            trusted_ca:
              filename: /etc/ssl/certs/ca-certificates.crt
  - name: admin
    connect_timeout: 5s
    type: LOGICAL_DNS
    dns_lookup_family: V4_ONLY
    load_assignment:
      cluster_name: admin
      endpoints:
        - lb_endpoints:
            - endpoint:
                address:
                  socket_address: 
                    address: webhook.site
                    port_value: 9901      
  - name: ext-proc
    connect_timeout: 5s
    type: strict_dns
    lb_policy: round_robin
    http2_protocol_options: { }
    load_assignment:
      cluster_name: ext-proc
      endpoints:
        - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: localhost
                    port_value: 10000
